<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Option extends Model
{
    protected $table = 'options';
    protected $fillable = ['type', 'name', 'value', 'field_type'];

    public function is_entrance_field_type()
    {
        return $this->field_type == 'entrance';
    }

    public function is_exit_field_type()
    {
        return $this->field_type == 'exit';
    }

    public static function currency_options()
    {
        return '            
            <option value="PHP" selected="selected">Philippines Pesos</option>
            <option value="USD">United States Dollars</option>
            <option value="EUR">Euro</option>
            <option value="GBP">United Kingdom Pounds</option>
            <option value="DZD">Algeria Dinars</option>
            <option value="ARP">Argentina Pesos</option>
            <option value="AUD">Australia Dollars</option>
            <option value="ATS">Austria Schillings</option>
            <option value="BSD">Bahamas Dollars</option>
            <option value="BBD">Barbados Dollars</option>
            <option value="BEF">Belgium Francs</option>
            <option value="BMD">Bermuda Dollars</option>
            <option value="BRR">Brazil Real</option>
            <option value="BGL">Bulgaria Lev</option>
            <option value="CAD">Canada Dollars</option>
            <option value="CLP">Chile Pesos</option>
            <option value="CNY">China Yuan Renmimbi</option>
            <option value="CYP">Cyprus Pounds</option>
            <option value="CSK">Czech Republic Koruna</option>
            <option value="DKK">Denmark Kroner</option>
            <option value="NLG">Dutch Guilders</option>
            <option value="XCD">Eastern Caribbean Dollars</option>
            <option value="EGP">Egypt Pounds</option>
            <option value="FJD">Fiji Dollars</option>
            <option value="FIM">Finland Markka</option>
            <option value="FRF">France Francs</option>
            <option value="DEM">Germany Deutsche Marks</option>
            <option value="XAU">Gold Ounces</option>
            <option value="GRD">Greece Drachmas</option>
            <option value="HKD">Hong Kong Dollars</option>
            <option value="HUF">Hungary Forint</option>
            <option value="ISK">Iceland Krona</option>
            <option value="INR">India Rupees</option>
            <option value="IDR">Indonesia Rupiah</option>
            <option value="IEP">Ireland Punt</option>
            <option value="ILS">Israel New Shekels</option>
            <option value="ITL">Italy Lira</option>
            <option value="JMD">Jamaica Dollars</option>
            <option value="JPY">Japan Yen</option>
            <option value="JOD">Jordan Dinar</option>
            <option value="KRW">Korea (South) Won</option>
            <option value="LBP">Lebanon Pounds</option>
            <option value="LUF">Luxembourg Francs</option>
            <option value="MYR">Malaysia Ringgit</option>
            <option value="MXP">Mexico Pesos</option>
            <option value="NLG">Netherlands Guilders</option>
            <option value="NZD">New Zealand Dollars</option>
            <option value="NOK">Norway Kroner</option>
            <option value="PKR">Pakistan Rupees</option>
            <option value="XPD">Palladium Ounces</option>
            <option value="XPT">Platinum Ounces</option>
            <option value="PLZ">Poland Zloty</option>
            <option value="PTE">Portugal Escudo</option>
            <option value="ROL">Romania Leu</option>
            <option value="RUR">Russia Rubles</option>
            <option value="SAR">Saudi Arabia Riyal</option>
            <option value="XAG">Silver Ounces</option>
            <option value="SGD">Singapore Dollars</option>
            <option value="SKK">Slovakia Koruna</option>
            <option value="ZAR">South Africa Rand</option>
            <option value="KRW">South Korea Won</option>
            <option value="ESP">Spain Pesetas</option>
            <option value="XDR">Special Drawing Right (IMF)</option>
            <option value="SDD">Sudan Dinar</option>
            <option value="SEK">Sweden Krona</option>
            <option value="CHF">Switzerland Francs</option>
            <option value="TWD">Taiwan Dollars</option>
            <option value="THB">Thailand Baht</option>
            <option value="TTD">Trinidad and Tobago Dollars</option>
            <option value="TRL">Turkey Lira</option>
            <option value="VEB">Venezuela Bolivar</option>
            <option value="ZMK">Zambia Kwacha</option>
            <option value="EUR">Euro</option>
            <option value="XCD">Eastern Caribbean Dollars</option>
            <option value="XDR">Special Drawing Right (IMF)</option>
            <option value="XAG">Silver Ounces</option>
            <option value="XAU">Gold Ounces</option>
            <option value="XPD">Palladium Ounces</option>
            <option value="XPT">Platinum Ounces</option>
        ';
    }

    public static function uom_options()
    {
        return '
            <option value="PC" selected="selected">PC - Piece</option>
            <option value="AB">AB - Bulk Pack</option>
            <option value="AF">AF - Centigram</option>
            <option value="AQ">AQ - Anti-hemophilic Factor (AHF) Units</option>
            <option value="AR">AR - Suppository</option>
            <option value="ASSY">ASSY - ASSYMBLE</option>
            <option value="AU">AU - Ocular Insert System</option>
            <option value="AV">AV - Capsule</option>
            <option value="AW">AW - Powder-Filled Vials</option>
            <option value="AZ">AZ - British Thermal Units (BTUs) per Pound</option>
            <option value="B0">B0 - British Thermal Units (BTUs) per Cubic Foot</option>
            <option value="B7">B7 - Cycles</option>
            <option value="BA">BA - Bale</option>
            <option value="BC">BC - Bucket</option>
            <option value="BD">BD - Bundle</option>
            <option value="BG">BG - Bag</option>
            <option value="BJ">BJ - Band</option>
            <option value="BK">BK - Book</option>
            <option value="BN">BN - Bulk</option>
            <option value="BO">BO - Bottle</option>
            <option value="BU">BU - Bushel</option>
            <option value="BW">BW - Base Weight</option>
            <option value="BX">BX - Box</option>
            <option value="BY">BY - British Thermal Unit (BTU)</option>
            <option value="BZ">BZ - Million?BTU"s</option>
            <option value="C1">C1 - Composite Product Pounds (Total Weight)</option>
            <option value="C3">C3 - Centiliter</option>
            <option value="C4">C4 - Carload</option>
            <option value="C6">C6 - Cell</option>
            <option value="C8">C8 - Cubic Decimeter</option>
            <option value="CA">CA - Case</option>
            <option value="CB">CB - Carboy</option>
            <option value="CC">CC - Cubic Centimeter</option>
            <option value="CD">CD - Carat</option>
            <option value="CE">CE - Centigrade, Celsius</option>
            <option value="CF">CF - Cubic Feet</option>
            <option value="CG">CG - Card</option>
            <option value="CH">CH - Container</option>
            <option value="CI">CI - Cubic Inches</option>
            <option value="CJ">CJ - Cone</option>
            <option value="CK">CK - Connector</option>
            <option value="CL">CL - Cylinder</option>
            <option value="CM">CM - Centimeter</option>
            <option value="CN">CN - Can</option>
            <option value="CO">CO - Cubic Meters (Net)</option>
            <option value="CP">CP - Crate</option>
            <option value="CQ">CQ - Cartridge</option>
            <option value="CR">CR - Cubic Meter</option>
            <option value="CS">CS - Cassette</option>
            <option value="CT">CT - Carton</option>
            <option value="CU">CU - Cup</option>
            <option value="CV">CV - Cover</option>
            <option value="CW">CW - Hundred Pounds (CWT)</option>
            <option value="CX">CX - Coil</option>
            <option value="CY">CY - Cubic Yard</option>
            <option value="D3">D3 - Square Decimeter</option>
            <option value="D5">D5 - Kilogram Per Square Centimeter</option>
            <option value="D9">D9 - Dyne per Square Centimeter</option>
            <option value="DA">DA - Days</option>
            <option value="DB">DB - Dry Pounds</option>
            <option value="DC">DC - Disk (Disc)</option>
            <option value="DD">DD - Degree</option>
            <option value="DE">DE - Deal</option>
            <option value="DF">DF - Dram</option>
            <option value="DG">DG - Decigram</option>
            <option value="DI">DI - Dispenser</option>
            <option value="DJ">DJ - Decagram</option>
            <option value="DK">DK - Kilometers</option>
            <option value="DL">DL - Deciliter</option>
            <option value="DM">DM - Decimeter</option>
            <option value="DO">DO - Dollars,?U.S.</option>
            <option value="DP">DP - Dozen Pair</option>
            <option value="DR">DR - Drum</option>
            <option value="DT">DT - Dry Ton</option>
            <option value="DZ">DZ - Dozen</option>
            <option value="E3">E3 - Inches, Fraction--Average</option>
            <option value="E4">E4 - Inches, Fraction--Minimum</option>
            <option value="E5">E5 - Inches, Fraction--Actual</option>
            <option value="E7">E7 - Inches, Decimal--Average</option>
            <option value="E8">E8 - Inches, Decimal--Actual</option>
            <option value="E9">E9 - English, (Feet, Inches)</option>
            <option value="EA">EA - Each</option>
            <option value="EC">EC - Each per Month</option>
            <option value="ED">ED - Inches, Decimal--Nominal</option>
            <option value="EF">EF - Inches, Fraction-Nominal</option>
            <option value="EG">EG - Double-time Hours</option>
            <option value="EM">EM - Inches, Decimal-Minimum</option>
            <option value="EP">EP - Eleven pack</option>
            <option value="EV">EV - Envelope</option>
            <option value="EX">EX - Feet, Inches and Fraction</option>
            <option value="EY">EY - Feet, Inches and Decimal</option>
            <option value="EZ">EZ - Feet and Decimal</option>
            <option value="F1">F1 - Thousand Cubic Feet Per Day</option>
            <option value="F2">F2 - International Unit</option>
            <option value="F4">F4 - Minim</option>
            <option value="F5">F5 - MOL</option>
            <option value="F9">F9 - Fibers per Cubic Centimeter of Air</option>
            <option value="FA">FA - Fahrenheit</option>
            <option value="FB">FB - Fields</option>
            <option value="FC">FC - 1000 Cubic Feet</option>
            <option value="FD">FD - Million Particles per Cubic Foot</option>
            <option value="FF">FF - Hundred Cubic Meters</option>
            <option value="FG">FG - Transdermal?Patch</option>
            <option value="FH">FH - Micromolar</option>
            <option value="FJ">FJ - Sizing Factor</option>
            <option value="FK">FK - Fibers</option>
            <option value="FL">FL - Flake Ton</option>
            <option value="FM">FM - Million Cubic Feet</option>
            <option value="FO">FO - Fluid Ounce</option>
            <option value="FP">FP - Pounds per Sq. Ft.</option>
            <option value="FT">FT - Foot</option>
            <option value="FZ">FZ - Fluid Ounce (Imperial)</option>
            <option value="G2">G2 - U.S. Gallons Per Minute</option>
            <option value="G3">G3 - Imperial Gallons Per Minute</option>
            <option value="G4">G4 - Gigabecquerel</option>
            <option value="GA">GA - Gallon</option>
            <option value="GB">GB - Gallons/Day</option>
            <option value="GC">GC - Grams per 100 Grams</option>
            <option value="GD">GD - Gross Barrels</option>
            <option value="GE">GE - Pounds per Gallon</option>
            <option value="GF">GF - Grams per 100 Centimeters</option>
            <option value="GG">GG - Great Gross (Dozen Gross)</option>
            <option value="GH">GH - Half Gallon</option>
            <option value="GI">GI - Imperial Gallons</option>
            <option value="GJ">GJ - Grams per Milliliter</option>
            <option value="GK">GK - Grams per Kilogram</option>
            <option value="GL">GL - Grams per Liter</option>
            <option value="GM">GM - Grams per Sq. Meter</option>
            <option value="GN">GN - Gross Gallons</option>
            <option value="GO">GO - Milligrams per Square Meter</option>
            <option value="GP">GP - Milligrams per Cubic Meter</option>
            <option value="GQ">GQ - Micrograms per Cubic Meter</option>
            <option value="GR">GR - Gram</option>
            <option value="GS">GS - Gross</option>
            <option value="GT">GT - Gross Kilogram</option>
            <option value="GU">GU - Gauss per?Oersteds</option>
            <option value="GW">GW - Gallons Per Thousand Cubic Feet</option>
            <option value="GX">GX - Grain</option>
            <option value="GY">GY - Gross Yard</option>
            <option value="GZ">GZ - Gage Systems</option>
            <option value="H2">H2 - Half Liter</option>
            <option value="H4">H4 - Hectoliter</option>
            <option value="HB">HB - Hundred Boxes</option>
            <option value="HC">HC - Hundred Count</option>
            <option value="HD">HD - Half Dozen</option>
            <option value="HE">HE - Hundredth of a Carat</option>
            <option value="HF">HF - Hundred Feet</option>
            <option value="HG">HG - Hectogram</option>
            <option value="HH">HH - Hundred Cubic Feet</option>
            <option value="HI">HI - Hundred Sheets</option>
            <option value="HK">HK - Hundred Kilograms</option>
            <option value="HL">HL - Hundred Feet - Linear</option>
            <option value="HN">HN - Millimeters of Mercury</option>
            <option value="HO">HO - Hundred?Troy?Ounces</option>
            <option value="HP">HP - Millimeter H20</option>
            <option value="HR">HR - Hours</option>
            <option value="HS">HS - Hundred Square Feet</option>
            <option value="HT">HT - Half Hour</option>
            <option value="HU">HU - Hundred</option>
            <option value="HV">HV - Hundred Weight (Short)</option>
            <option value="HW">HW - Hundred Weight (Long)</option>
            <option value="HY">HY - Hundred Yards</option>
            <option value="IA">IA - Inch Pound</option>
            <option value="IH">IH - Inhaler</option>
            <option value="IM">IM - Impressions</option>
            <option value="IN">IN - Inch</option>
            <option value="J2">J2 - Joule Per Kilogram</option>
            <option value="JE">JE - Joule Per Kelvin</option>
            <option value="JG">JG - Joule per Gram</option>
            <option value="JK">JK - Mega Joule per Kilogram</option>
            <option value="JM">JM - Megajoule/Cubic Meter</option>
            <option value="JO">JO - Joint</option>
            <option value="JR">JR - Jar</option>
            <option value="KG">KG - Kilogram</option>
            <option value="KR">KR - Kiloroentgen</option>
            <option value="KS">KS - 1000 Pounds per Square Inch</option>
            <option value="KW">KW - Kilograms per Millimeter</option>
            <option value="KX">KX - Milliliters per Kilogram</option>
            <option value="L2">L2 - Liters Per Minute</option>
            <option value="LA">LA - Pounds Per Cubic Inch</option>
            <option value="LB">LB - Pound</option>
            <option value="LC">LC - Linear Centimeter</option>
            <option value="LF">LF - Linear Foot</option>
            <option value="LI">LI - Linear Inch</option>
            <option value="LM">LM - Linear Meter</option>
            <option value="LP">LP - Liquid Pounds</option>
            <option value="LQ">LQ - Liters Per Day</option>
            <option value="LR">LR - Layer(s)</option>
            <option value="LS">LS - Lump Sum</option>
            <option value="LT">LT - Liter</option>
            <option value="LX">LX - Linear Yards Per Pound</option>
            <option value="LY">LY - Linear Yard</option>
            <option value="M1">M1 - Milligrams per Liter</option>
            <option value="M2">M2 - Millimeter-Actual</option>
            <option value="M5">M5 - Microcurie</option>
            <option value="M6">M6 - Millibar</option>
            <option value="M7">M7 - Micro Inch</option>
            <option value="M8">M8 - Mega Pascals</option>
            <option value="M9">M9 - Million British Thermal Units per One Thousand Cubic Feet</option>
            <option value="MB">MB - Millimeter-Nominal</option>
            <option value="MC">MC - Microgram</option>
            <option value="MD">MD - Air Dry Metric Ton</option>
            <option value="ME">ME - Milligram</option>
            <option value="MF">MF - Milligram per Sq. Ft. per Side</option>
            <option value="MG">MG - Metric Gross Ton</option>
            <option value="MH">MH - Microns (Micrometers)</option>
            <option value="MI">MI - Metric</option>
            <option value="MJ">MJ - Minutes</option>
            <option value="MK">MK - Milligrams Per Square Inch</option>
            <option value="ML">ML - Milliliter</option>
            <option value="MM">MM - Millimeter</option>
            <option value="MN">MN - Metric Net Ton</option>
            <option value="MO">MO - Months</option>
            <option value="MP">MP - Metric Ton</option>
            <option value="MQ">MQ - 1000 Meters</option>
            <option value="MR">MR - Meter</option>
            <option value="MS">MS - Square Millimeter</option>
            <option value="MT">MT - Metric Long Ton</option>
            <option value="MU">MU - Millicurie</option>
            <option value="MW">MW - Metric Ton Kilograms</option>
            <option value="MX">MX - Mixed</option>
            <option value="MY">MY - Millimeter-Average</option>
            <option value="NA">NA - Milligrams per Kilogram</option>
            <option value="NB">NB - Barge</option>
            <option value="NC">NC - Car</option>
            <option value="ND">ND - Net Barrels</option>
            <option value="NE">NE - Net Liters</option>
            <option value="NG">NG - Net Gallons</option>
            <option value="NI">NI - Net Imperial Gallons</option>
            <option value="NX">NX - Parts Per Thousand</option>
            <option value="NY">NY - Pounds Per Air-Dry Metric Ton</option>
            <option value="ON">ON - Ounces per Square Yard</option>
            <option value="OP">OP - Two pack</option>
            <option value="OZ">OZ - Ounce - Av</option>
            <option value="P1">P1 - Percent</option>
            <option value="P2">P2 - Pounds per Foot</option>            
            <option value="PD">PD - Pad</option>
            <option value="PE">PE - Pounds Equivalent</option>
            <option value="PF">PF - Pallet (Lift)</option>
            <option value="PG">PG - Pounds Gross</option>
            <option value="PM">PM - Pounds-Percentage</option>
            <option value="PN">PN - Pounds Net</option>
            <option value="PO">PO - Pounds per Inch of Length</option>
            <option value="PP">PP - Plate</option>
            <option value="PR">PR - Pair</option>
            <option value="PS">PS - Pounds per Sq. Inch</option>
            <option value="PT">PT - Pint</option>
            <option value="PU">PU - Mass Pounds</option>
            <option value="PW">PW - Pounds per Inch of Width</option>
            <option value="PX">PX - Pint, Imperial</option>
            <option value="PY">PY - Peck, Dry?U.S.</option>
            <option value="PZ">PZ - Peck, Dry Imperial</option>
            <option value="Q2">Q2 - Pint?U.S.?Dry</option>
            <option value="QR">QR - Quire</option>
            <option value="QS">QS - Quart, Dry?U.S.</option>
            <option value="QT">QT - Quart</option>
            <option value="QU">QU - Quart, Imperial</option>
            <option value="R9">R9 - Thousand Cubic Meters</option>
            <option value="RA">RA - Rack</option>
            <option value="RB">RB - Radian</option>
            <option value="RC">RC - Rod (area) - 16.25 Square Yards</option>
            <option value="RD">RD - Rod (length) - 5.5 Yards</option>
            <option value="RE">RE - Reel</option>
            <option value="RK">RK - Roll-Metric Measure</option>
            <option value="RL">RL - Roll</option>
            <option value="RM">RM - Ream</option>
            <option value="RN">RN - Ream-Metric Measure</option>
            <option value="RO">RO - Round</option>
            <option value="RP">RP - Pounds per Ream</option>
            <option value="S5">S5 - Sixty-fourths of an Inch</option>
            <option value="SC">SC - Square Centimeter</option>
            <option value="SD">SD - Solid Pounds</option>
            <option value="SF">SF - Square Foot</option>
            <option value="SG">SG - Segment</option>
            <option value="SH">SH - Sheet</option>
            <option value="SI">SI - Square Inch</option>
            <option value="SJ">SJ - Sack</option>
            <option value="SL">SL - Sleeve</option>
            <option value="SM">SM - Square Meter</option>
            <option value="SN">SN - Square Rod</option>
            <option value="SO">SO - Spool</option>
            <option value="SP">SP - Shelf Package</option>
            <option value="SR">SR - Strip</option>
            <option value="SS">SS - Sheet-Metric Measure</option>
            <option value="ST">ST - Set</option>
            <option value="SV">SV - Skid</option>
            <option value="SX">SX - Shipment</option>
            <option value="SY">SY - Square Yard</option>
            <option value="SZ">SZ - Syringe</option>
            <option value="T1">T1 - Thousand pounds gross</option>
            <option value="T2">T2 - Thousandths of an Inch</option>
            <option value="T3">T3 - Thousand Pieces</option>
            <option value="T4">T4 - Thousand Bags</option>
            <option value="T5">T5 - Thousand Casings</option>
            <option value="T6">T6 - Thousand Gallons</option>
            <option value="T7">T7 - Thousand Impressions</option>
            <option value="T8">T8 - Thousand Linear Inches</option>
            <option value="T9">T9 - Thousand Kilowatt Hours</option>
            <option value="TA">TA - Tenth Cubic Foot</option>
            <option value="TB">TB - Tube</option>
            <option value="TC">TC - Truckload</option>
            <option value="TD">TD - Therms</option>
            <option value="TE">TE - Tote</option>
            <option value="TF">TF - Ten Square Yards</option>
            <option value="TG">TG - Gross Ton</option>
            <option value="TH">TH - Thousand</option>
            <option value="TI">TI - Thousand Square Inches</option>
            <option value="TJ">TJ - Thousand Sq. Centimeters</option>
            <option value="TK">TK - Tank</option>
            <option value="TL">TL - Thousand Feet (Linear)</option>
            <option value="TM">TM - Thousand Feet (Board)</option>
            <option value="TN">TN - Net Ton (2,000 LB).</option>
            <option value="TO">TO - Troy Ounce</option>
            <option value="TP">TP - Ten-pack</option>
            <option value="TQ">TQ - Thousand Feet</option>
            <option value="TR">TR - Ten Square Feet</option>
            <option value="TS">TS - Thousand Square Feet</option>
            <option value="TT">TT - Thousand Linear Meters</option>
            <option value="TU">TU - Thousand Linear Yards</option>
            <option value="TV">TV - Thousand Kilograms</option>
            <option value="TW">TW - Thousand Sheets</option>
            <option value="TX">TX - Troy Pound</option>
            <option value="TY">TY - Tray</option>
            <option value="TZ">TZ - Thousand Cubic Feet</option>
            <option value="U1">U1 - Treatments</option>
            <option value="U2">U2 - Tablet</option>
            <option value="U3">U3 - Ten</option>
            <option value="U5">U5 - Two Hundred Fifty</option>
            <option value="UH">UH - Ten Thousand Yards</option>
            <option value="UL">UL - Unitless</option>
            <option value="UM">UM - Million Units</option>
            <option value="UN">UN - Unit</option>
            <option value="UP">UP - Troche</option>
            <option value="US">US - Dosage Form</option>
            <option value="UT">UT - Inhalation</option>
            <option value="UU">UU - Lozenge</option>
            <option value="UV">UV - Percent Topical Only</option>
            <option value="UW">UW - Milliequivalent</option>
            <option value="UX">UX - Dram (Minim)</option>
            <option value="UY">UY - Fifty Square Feet</option>
            <option value="UZ">UZ - Fifty Count</option>
            <option value="VC">VC - Five Hundred</option>
            <option value="VI">VI - Vial</option>
            <option value="VP">VP - Percent Volume</option>
            <option value="VS">VS - Visit</option>
            <option value="WD">WD - Work Days</option>
            <option value="WP">WP - Pennyweight</option>
            <option value="WR">WR - Wrap</option>
            <option value="X2">X2 - Bunch</option>
            <option value="X4">X4 - Drop</option>
            <option value="Y2">Y2 - Tablespoon</option>
            <option value="Y3">Y3 - Teaspoon</option>
            <option value="Y4">Y4 - Tub</option>
            <option value="YD">YD - Yard</option>
            <option value="YL">YL - 100 Lineal Yards</option>
            <option value="YT">YT - Ten Yards</option>
            <option value="Z3">Z3 - Cask</option>
        ';
    }
}
